# Generated by Django 3.2.6 on 2021-08-12 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sir_name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_photo', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='metrimony/images')),
                ('mother_tongue', models.CharField(blank=True, max_length=100, null=True)),
                ('diet', models.CharField(blank=True, choices=[('Vegetarian', 'Vegetarian'), ('Non-Vegetarian', 'Non-Vegetarian')], max_length=100, null=True)),
                ('do_u_smoke', models.CharField(blank=True, max_length=100, null=True)),
                ('do_u_drink', models.CharField(blank=True, max_length=100, null=True)),
                ('have_child', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('residency_country', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_country', models.CharField(blank=True, max_length=100, null=True)),
                ('grow_up_country', models.CharField(blank=True, max_length=100, null=True)),
                ('present_address', models.TextField(blank=True, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('work_location', models.CharField(blank=True, max_length=100, null=True)),
                ('employed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('working_from', models.CharField(blank=True, choices=[('Home', 'Home'), ('Office', 'Office'), ('Remote', 'Remote')], max_length=100, null=True)),
                ('no_of_boy_child_of_your_father', models.IntegerField(blank=True, null=True)),
                ('no_of_girl_child_of_your_father', models.IntegerField(blank=True, null=True)),
                ('family_type', models.CharField(blank=True, choices=[('Joint', 'Joint'), ('Nuclear', 'Nuclear')], max_length=100, null=True)),
                ('family_status', models.CharField(blank=True, choices=[('Affluent', 'Affluent'), ('Lower Middle Class', 'Lower Middle Class'), ('Middle Class', 'Middle Class'), ('Higher Middle Class', 'Higher Middle Class'), ('Rich', 'Rich')], max_length=100, null=True)),
                ('eye_color', models.CharField(blank=True, max_length=100, null=True)),
                ('hair_color', models.CharField(blank=True, max_length=100, null=True)),
                ('hair_style', models.CharField(blank=True, max_length=100, null=True)),
                ('complexion', models.CharField(blank=True, max_length=100, null=True)),
                ('any_disability', models.CharField(blank=True, max_length=100, null=True)),
                ('body_type', models.CharField(blank=True, max_length=100, null=True)),
                ('interest', models.TextField(blank=True, null=True)),
                ('music', models.TextField(blank=True, null=True)),
                ('read_books', models.TextField(blank=True, null=True)),
                ('tv_shows', models.TextField(blank=True, null=True)),
                ('sports_shows', models.TextField(blank=True, null=True)),
                ('sports', models.TextField(blank=True, null=True)),
                ('fav_dress_style', models.TextField(blank=True, null=True)),
                ('fav_color', models.CharField(blank=True, max_length=100, null=True)),
                ('know_dancing', models.CharField(blank=True, max_length=100, null=True)),
                ('know_singing', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expectaion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.CharField(blank=True, max_length=100, null=True)),
                ('max_age', models.CharField(blank=True, max_length=100, null=True)),
                ('min_height', models.CharField(blank=True, max_length=100, null=True)),
                ('max_height', models.CharField(blank=True, max_length=100, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Married', 'Married'), ('Never Married', 'Never Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Awaiting Divorces', 'Awaiting Divorces')], max_length=100, null=True)),
                ('with_childern', models.CharField(blank=True, max_length=100, null=True)),
                ('residency_country', models.CharField(blank=True, max_length=100, null=True)),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('complexion', models.CharField(blank=True, max_length=100, null=True)),
                ('education', models.CharField(blank=True, max_length=100, null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('drinking_havits', models.CharField(blank=True, max_length=100, null=True)),
                ('smoking_habits', models.CharField(blank=True, max_length=100, null=True)),
                ('diet', models.CharField(blank=True, choices=[('Vegetarian', 'Vegetarian'), ('Non-Vegetarian', 'Non-Vegetarian')], max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ecpectationprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
