# Generated by Django 3.2.6 on 2021-10-09 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metrimony', '0005_alter_expectaion_min_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal_info',
            old_name='full_name',
            new_name='guardians_type',
        ),
        migrations.RenameField(
            model_name='personal_info',
            old_name='sir_name',
            new_name='sur_name',
        ),
        migrations.AddField(
            model_name='personal_info',
            name='guardians_phone',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='privary_limit',
            field=models.ManyToManyField(blank=True, related_name='matrimony_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='VisaVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa_no', models.CharField(blank=True, max_length=100, null=True)),
                ('visa_type', models.CharField(blank=True, max_length=100, null=True)),
                ('visa_country', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('visa_image', models.ImageField(blank=True, null=True, upload_to='metrimony/visa')),
                ('visa_varified', models.BooleanField(default=False)),
                ('matrimony', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visa', to='metrimony.personal_info')),
            ],
        ),
    ]
