# Generated by Django 3.2.6 on 2021-10-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrimony', '0006_auto_20211009_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_info',
            name='birth_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='metrimony/birth_certificate'),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='nid_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='passport_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='passport_verified',
            field=models.BooleanField(default=False),
        ),
    ]
