# Generated by Django 3.2.6 on 2021-10-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrimony', '0009_auto_20211011_0628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expectaion',
            old_name='annual_income',
            new_name='annual_income_max',
        ),
        migrations.AddField(
            model_name='expectaion',
            name='annual_income_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
