# Generated by Django 3.2.6 on 2021-10-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrimony', '0010_auto_20211011_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_info',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
    ]
