# Generated by Django 3.2.6 on 2021-10-11 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrimony', '0011_personal_info_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expectaion',
            old_name='annual_income_max',
            new_name='monthly_income_max',
        ),
        migrations.RenameField(
            model_name='expectaion',
            old_name='annual_income_min',
            new_name='monthly_income_min',
        ),
    ]
