# Generated by Django 3.2.6 on 2021-10-12 03:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metrimony', '0012_auto_20211011_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_info',
            name='viewed_by',
            field=models.ManyToManyField(blank=True, related_name='matrimony_viewed', to=settings.AUTH_USER_MODEL),
        ),
    ]
