# Generated by Django 3.2.6 on 2021-10-12 03:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metrimony', '0013_personal_info_viewed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_info',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='metrimony/images'),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='metrimony/images'),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='viewed',
            field=models.ManyToManyField(blank=True, related_name='matrimony_viewed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
