# Generated by Django 3.2.6 on 2021-10-12 03:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metrimony', '0014_auto_20211012_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_info',
            name='interested',
            field=models.ManyToManyField(blank=True, related_name='matrimony_interested_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='interested_by',
            field=models.ManyToManyField(blank=True, related_name='matrimony_interested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='pending_interested_by',
            field=models.ManyToManyField(blank=True, related_name='pending_matrimony_interested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='shortlisted',
            field=models.ManyToManyField(blank=True, related_name='matrimony_shortlisted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
