# Generated by Django 3.2.6 on 2021-10-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrimony', '0017_alter_visaverification_visa_varified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaverification',
            name='visa_varified',
            field=models.BooleanField(default=False),
        ),
    ]
