# Generated by Django 3.2.6 on 2021-10-28 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrimony', '0018_alter_visaverification_visa_varified'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriBlockList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_blocked_by', to='metrimony.personal_info')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_block_list', to='metrimony.personal_info')),
            ],
        ),
        migrations.CreateModel(
            name='MatriBlockedBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ms_block_list', to='metrimony.personal_info')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ma_blocked_by', to='metrimony.personal_info')),
            ],
        ),
        migrations.AddField(
            model_name='personal_info',
            name='block_list',
            field=models.ManyToManyField(blank=True, related_name='_metrimony_personal_info_block_list_+', through='metrimony.MatriBlockList', to='metrimony.Personal_Info'),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='blocked_by',
            field=models.ManyToManyField(blank=True, related_name='_metrimony_personal_info_blocked_by_+', through='metrimony.MatriBlockedBy', to='metrimony.Personal_Info'),
        ),
    ]
