# Generated by Django 3.2.6 on 2021-10-28 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metrimony', '0020_auto_20211028_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriblockedby',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ma_blocked_by', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matriblocklist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='m_block_list', to='auth.user'),
            preserve_default=False,
        ),
    ]
