# Generated by Django 3.2.6 on 2021-10-28 09:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metrimony', '0021_auto_20211028_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='block_list',
            field=models.ManyToManyField(blank=True, related_name='matri_blocked_by', through='metrimony.MatriBlockList', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='blocked_by',
            field=models.ManyToManyField(blank=True, related_name='matri_block_list', through='metrimony.MatriBlockedBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
