# Generated by Django 3.2.6 on 2021-08-18 02:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapp', '0002_coverphoto_profilephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilephoto',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='dp_tag', to=settings.AUTH_USER_MODEL),
        ),
    ]
