# Generated by Django 3.2.6 on 2021-08-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_profilephoto_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverphoto',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profilephoto',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
