version: "3"

services:
  frontend:
    container_name: front
    restart: always
    build:
      context: .
      dockerfile: ./public/Dockerfile
    command : npm start
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - ./:/Demo/
      - node_modules:/Demo/node_modules
   
  web:
    container_name: back
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    links:
    - redis
    volumes:
      - ./:/Demo/
  redis:
    image: redis:latest
    container_name: rd01
    # command: redis-server
    ports:
    - '6379:6379'
volumes:
  node_modules:
