# Generated by Django 3.2.6 on 2021-08-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
