# Generated by Django 3.2.6 on 2021-09-01 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_consumer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='can_follow',
            field=models.BooleanField(default=True),
        ),
    ]
