# Generated by Django 3.2.6 on 2021-08-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeling',
            name='emoji',
            field=models.ImageField(blank=True, null=True, upload_to='images/emojis'),
        ),
        migrations.AddField(
            model_name='feeling',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
