# Generated by Django 3.2.6 on 2021-08-21 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0002_auto_20210821_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/reacts')),
            ],
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_hqa', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='activity_post', to='social.activity')),
                ('angry', models.ManyToManyField(blank=True, related_name='post_angries', to=settings.AUTH_USER_MODEL)),
                ('background', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='background_post', to='social.backgroud')),
                ('care', models.ManyToManyField(blank=True, related_name='post_cares', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_post', to='social.category')),
                ('check_in', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='location_post', to='social.check_in')),
                ('feeling', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='feeling_post', to='social.feeling')),
                ('gif', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gif_post', to='social.gif')),
                ('haha', models.ManyToManyField(blank=True, related_name='post_hahas', to=settings.AUTH_USER_MODEL)),
                ('lifeevent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lifeevent_post', to='social.lifeevent')),
                ('likes', models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL)),
                ('love', models.ManyToManyField(blank=True, related_name='post_loves', to=settings.AUTH_USER_MODEL)),
                ('privacy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='privacy_post', to='social.privacy')),
                ('sad', models.ManyToManyField(blank=True, related_name='post_sads', to=settings.AUTH_USER_MODEL)),
                ('senti', models.ManyToManyField(blank=True, related_name='post_senties', to=settings.AUTH_USER_MODEL)),
                ('shared_by', models.ManyToManyField(blank=True, related_name='shared_post', to=settings.AUTH_USER_MODEL)),
                ('subactivity', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subactivity_post', to='social.subactivity')),
                ('sublifeevent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sublifeevent_post', to='social.sublifeevent')),
                ('tags', models.ManyToManyField(blank=True, related_name='taglist', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_post', to=settings.AUTH_USER_MODEL)),
                ('wow', models.ManyToManyField(blank=True, related_name='post_wows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
