# Generated by Django 3.2.6 on 2021-08-21 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0004_rename_privacy_privacymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpost',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='activity_post', to='social.activity'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='angry',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_angries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='background_post', to='social.backgroud'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='care',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_cares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='check_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='location_post', to='social.check_in'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='feeling',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='feeling_post', to='social.feeling'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='gif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gif_post', to='social.gif'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='haha',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_hahas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='lifeevent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lifeevent_post', to='social.lifeevent'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='love',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_loves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='sad',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_sads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='senti',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_senties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='shared_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='shared_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='subactivity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subactivity_post', to='social.subactivity'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='sublifeevent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sublifeevent_post', to='social.sublifeevent'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='taglist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='wow',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_wows', to=settings.AUTH_USER_MODEL),
        ),
    ]
