# Generated by Django 3.2.6 on 2021-08-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20210822_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialupdatehistory',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
