# Generated by Django 3.2.6 on 2021-08-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_alter_socialupdatehistory_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialupdatehistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
