# Generated by Django 3.2.6 on 2021-08-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_socialphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
