# Generated by Django 3.2.6 on 2021-08-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_socialpost_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacymodel',
            name='icon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='privacymodel',
            name='nameSubtitle',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
