# Generated by Django 3.2.6 on 2021-08-26 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_auto_20210826_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['rank']},
        ),
        migrations.AlterModelOptions(
            name='backgroud',
            options={'ordering': ['rank']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['rank']},
        ),
        migrations.AlterModelOptions(
            name='check_in',
            options={'ordering': ['rank']},
        ),
        migrations.AlterModelOptions(
            name='feeling',
            options={'ordering': ['rank']},
        ),
        migrations.AlterModelOptions(
            name='gif',
            options={'ordering': ['rank']},
        ),
        migrations.AlterModelOptions(
            name='lifeevent',
            options={'ordering': ['rank']},
        ),
        migrations.AlterModelOptions(
            name='privacymodel',
            options={'ordering': ['rank']},
        ),
        migrations.AlterModelOptions(
            name='subactivity',
            options={'ordering': ['rank']},
        ),
        migrations.AlterModelOptions(
            name='sublifeevent',
            options={'ordering': ['rank']},
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_post', to='social.activity'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background_post', to='social.backgroud'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_post', to='social.category'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='check_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_post', to='social.check_in'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='feeling',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeling_post', to='social.feeling'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='gif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gif_post', to='social.gif'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='lifeevent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifeevent_post', to='social.lifeevent'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='privacy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='privacy_post', to='social.privacymodel'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='subactivity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subactivity_post', to='social.subactivity'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='sublifeevent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sublifeevent_post', to='social.sublifeevent'),
        ),
    ]
