const allUsers=[
    {
        id: 120,
        iconType: "image",
        userName: "nazmul",
        imageUrl: "https://i.ibb.co/09QkpgB/av3.jpg",
        title: "Nazmul Ahsan",
        firstName: "Nazmul",
        lastName: "Ahsan",
        email: "xyz@gmail.com",
        phone: "1682335577",
        country: "Bangladesh",
        address1: "Bagura",
        address2: "Jahrul Nagar",
        gender: "Male",
        religion: "Islam",
      },
      {
        id: 150,
        iconType: "image",
        userName: "kabirkhan1921",
        imageUrl: "https://i.ibb.co/HzGqwCT/profile.png",
        title: "Humaion Kabir Khan Rahman",
        firstName: "Humaion Kabir",
        lastName: "Khan Rahman",
        email: "abcd@gmail.com",
        phone: "1715334455",
        country: "Bangladesh",
        address1: "Chittagong",
        address2: "Halishahr",
        gender: "Male",
        religion: "Islam",
      },
      {
        id: 155,
        iconType: "image",
        userName: "himu65",
        imageUrl: "https://i.ibb.co/wpgp6j3/av2.jpg",
        title: "Himu Mita",
        firstName: "Himu",
        lastName: "Mita",
        email: "mita@gmail.com",
        phone: "1682656565",
        country: "Bangladesh",
        address1: "Mirpur",
        address2: "Kacha Bazar, Radio colony",
        gender: "Male",
        religion: "Islam",
      },
      {
        id: 176,
        iconType: "image",
        userName: "shakib2021",
        imageUrl: "https://i.ibb.co/SsKs8Yh/av7.jpg",
        title: "Shakib Al Hasan",
        firstName: "Shakib",
        lastName: "Al Hasan",
        email: "shakib@gmail.com",
        phone: "1682656565",
        country: "Bangladesh",
        address1: "Dinajpur",
        address2: "Kacha Bazar, Radio colony",
        gender: "Male",
        religion: "Islam",
      },
      {
        id: 186,
        iconType: "image",
        userName: "hero007",
        imageUrl: "https://i.ibb.co/fqQCT08/av6.jpg",
        title: "Hero Alam Official",
        firstName: "Hero",
        lastName: "Alam Official",
        email: "hero@gmail.com",
        phone: "02343456",
        country: "Bangladesh",
        address1: "Rajshahi",
        address2: "Lal matha, kotowali",
        gender: "Male",
        religion: "Islam",
      },
      {
        id: 286,
        iconType: "image",
        userName: "joebaiden",
        imageUrl: "https://i.ibb.co/JR5NwLq/av5.jpg",
        title: "Joe Baiden",
        firstName: "Joe",
        lastName: "Baiden",
        email: "baiden@gmail.com",
        phone: "03343456",
        country: "Bangladesh",
        address1: "Khulna",
        address2: "Rupsha bridge housing",
        gender: "Female",
        religion: "Islam",
      },
      {
        id: 586,
        iconType: "image",
        userName: "trumpOriginal",
        imageUrl: "https://i.ibb.co/sJ0VPvk/av4.jpg",
        title: "Trump Original",
        firstName: "Trump",
        lastName: "Original",
        email: "trump@gmail.com",
        phone: "01543687",
        country: "Bangladesh",
        address1: "Barishal",
        address2: "Rupsha Bridge",
        gender: "Male",
        religion: "Islam",
      }
];
export default allUsers;