const homeLeftLayoutCardData = [
  {
    id: 2,
    iconType: "icon",
    imageUrl: "https://i.ibb.co/FgkhXzs/followers.png",
    title: "Follower",
    url: "follower",
    counter: 12,
    notification: 2,
  },
  {
    id: 3,
    iconType: "icon",
    imageUrl: "https://i.ibb.co/Rb7mmKw/following.png",
    title: "Following",
    url: "following",
    counter: 120,
    notification: 14,
  },
  {
    id: 4,
    iconType: "icon",
    imageUrl: "https://i.ibb.co/qWtqWVs/group.png",
    title: "Groups",
    url: "groups",
    counter: 14,
    notification: 13,
  },
  {
    id: 5,
    iconType: "icon",
    imageUrl: "https://i.ibb.co/5R4zDXV/page.png",
    title: "Pages",
    url: "pages",
    counter: 3,
    notification: 0,
  },
  {
    id: 6,
    iconType: "icon",
    imageUrl: "https://i.ibb.co/N26d2zr/jobsLeft.png",
    title: "Jobs",
    url: "new-jobs",
    counter: 0,
    notification: 6,
  },
  {
    id: 7,
    iconType: "icon",
    imageUrl: "https://i.ibb.co/T47ZJZs/resume.png",
    title: "Resume",
    url: "resume",
    counter: 0,
    notification: 0,
  },
  {
    id: 8,
    iconType: "icon",
    imageUrl: "https://i.ibb.co/z6PGztc/post.png",
    title: "Post",
    url: "posts",
    counter: 0,
    notification: 0,
  },
  {
    id: 9,
    iconType: "icon",
    imageUrl: "https://i.ibb.co/XX0BGgP/gallery.png",
    title: "Gallery",
    url: "gallery",
    counter: 0,
    notification: 0,
  },
  {
    id: 10,
    iconType: "icon",
    imageUrl: "https://i.ibb.co/kcvJ8Zx/live.png",
    title: "Live",
    url: "live",
    counter: 0,
    notification: 6,
  },
  {
    id: 11,
    iconType: "icon",
    imageUrl: "https://i.ibb.co/N26d2zr/jobsLeft.png",
    title: "Ad Manager",
    url: "ad-manager",
    counter: 0,
    notification: 0,
  },
  {
    id: 12,
    iconType: "icon",
    imageUrl: "https://i.ibb.co/JvwxvzC/blood-donation.png",
    title: "Blood Donation",
    url: "blood-donation",
    counter: 0,
    notification: 0,
  },
  {
    id: 13,
    iconType: "icon",
    imageUrl: "https://i.ibb.co/n6NJ57g/donation.png",
    title: "Donation",
    url: "donation",
    counter: 0,
    notification: 0,
  },
  {
    id: 14,
    iconType: "icon",
    imageUrl: "https://i.ibb.co/FsYrv0Y/charity.png",
    title: "Ehsan Charity",
    url: "ehsan-charity",
    counter: 0,
    notification: 0,
  },
];

export default homeLeftLayoutCardData;
