//If categoy group then actionAt will be null or empty
// If notification is pushed by the system then actionFor will be null or empty
const notifications = [
  {
    id: 321,
    actionType: "comment",
    actionAt: "post",
    whoDid: "Nazmul Ahsan, Rakibul Hasan and 3 others",
    actionGrammer: "commented on",
    actionFor: "Ehsan Software",
    url: "https://i.ibb.co/5R4zDXV/page.png",
    category: "page",
    iconUrl: "https://i.ibb.co/5R4zDXV/page.png",
    imageUrl: "https://i.ibb.co/09QkpgB/av3.jpg",
    text: "",
    date: "12/12/2020",
    time: "4:21pm",
    ago: "1 min ago",
  },
  {
    id: 221,
    actionType: "post",
    actionAt: "",
    whoDid: "Rakibul Hasan",
    actionGrammer: "posted in",
    actionFor: "Ehsan Group",
    url: "https://i.ibb.co/qWtqWVs/group.png",
    category: "group",
    iconUrl: "https://i.ibb.co/qWtqWVs/group.png",
    imageUrl: "	https://i.ibb.co/BCJjTdC/demo-Logo3.png",
    text: "Lorem Ipsum is simply dummy....",
    date: "12/12/2020",
    time: "4:21pm",
    ago: "4 hours ago",
  },
  {
    id: 11,
    actionType: "invitation",
    actionAt: "",
    whoDid: "Shamim Al Hasan",
    actionGrammer: "invited you to join the group",
    actionFor: "Noyakhali Mativanga High School 2007-09",
    url: "https://i.ibb.co/qWtqWVs/group.png",
    category: "group",
    iconUrl: "https://i.ibb.co/qWtqWVs/group.png",
    imageUrl: "https://i.ibb.co/80XNb9q/logo1.jpg",
    text: "",
    date: "12/12/2020",
    time: "4:21pm",
    ago: "7 hours ago",
  },
  {
    id: 9,
    actionType: "comment",
    actionAt: "post",
    whoDid: "Tanvir Musa, Reza and 18 others",
    actionGrammer: "commented on your",
    actionFor: "Shared Link",
    url: "",
    category: "your",
    iconUrl: "https://i.ibb.co/Krfh4bw/comment.png",
    imageUrl: "https://i.ibb.co/HzGqwCT/profile.png",
    text: "",
    date: "12/12/2020",
    time: "4:21pm",
    ago: "17 hours ago",
  },
  {
    id: 19,
    actionType: "approval",
    actionAt: "",
    whoDid: "Mehjabin",
    actionGrammer: "Approved your request to JOIN",
    actionFor: "Bagura Cricket Fan Group",
    url: "",
    category: "group",
    iconUrl: "https://i.ibb.co/qWtqWVs/group.png",
    imageUrl: "https://i.ibb.co/hXgdKPB/logo7.jpg",
    text: "",
    date: "12/12/2020",
    time: "4:21pm",
    ago: "1 days ago",
  },
  {
    id: 199,
    actionType: "job",
    actionAt: "",
    whoDid: "Web Developer and 16 Other JOBs",
    actionGrammer: "were posted that match your preferred job title",
    actionFor: "",
    url: "",
    category: "job",
    iconUrl: "https://i.ibb.co/N26d2zr/jobsLeft.png",
    imageUrl: "https://i.ibb.co/tmVYqsp/Job-openings.jpg",
    text: "",
    date: "12/12/2020",
    time: "4:21pm",
    ago: "1 days ago",
  },
  {
    id: 499,
    actionType: "like",
    actionAt: "page",
    whoDid: "Polash, Akhi and 128 others ",
    actionGrammer: "were liked your page",
    actionFor: "Fancy Bird Buy Sale",
    url: "",
    category: "page",
    iconUrl: "https://i.ibb.co/5R4zDXV/page.png",
    imageUrl:
      "https://i.ibb.co/cJJbJqG/vector-illustration-of-flying-eagle-symbol.jpg",
    text: "",
    date: "12/12/2020",
    time: "4:21pm",
    ago: "2 days ago",
  },
];

export default notifications;
