# Generated by Django 3.2.6 on 2021-08-26 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_socialpost_is_draft'),
        ('comment', '0002_photocomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photocomment',
            name='post',
        ),
        migrations.AddField(
            model_name='photocomment',
            name='photo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photo_comments', to='social.socialphoto'),
            preserve_default=False,
        ),
    ]
