# Generated by Django 3.2.6 on 2021-08-26 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_socialpost_is_draft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0003_auto_20210826_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocomment',
            name='angry',
            field=models.ManyToManyField(blank=True, related_name='p3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photocomment',
            name='care',
            field=models.ManyToManyField(blank=True, related_name='p6', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photocomment',
            name='haha',
            field=models.ManyToManyField(blank=True, related_name='p4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photocomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='p1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photocomment',
            name='love',
            field=models.ManyToManyField(blank=True, related_name='p2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photocomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comment.photocomment'),
        ),
        migrations.AlterField(
            model_name='photocomment',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_dgdcomments', to='social.socialphoto'),
        ),
        migrations.AlterField(
            model_name='photocomment',
            name='sad',
            field=models.ManyToManyField(blank=True, related_name='p5', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photocomment',
            name='senti',
            field=models.ManyToManyField(blank=True, related_name='p7', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photocomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_photoscomment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photocomment',
            name='wow',
            field=models.ManyToManyField(blank=True, related_name='p8', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PostPhotoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/photocomment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('angry', models.ManyToManyField(blank=True, related_name='photo_comment_angries', to=settings.AUTH_USER_MODEL)),
                ('care', models.ManyToManyField(blank=True, related_name='photo_comment_cares', to=settings.AUTH_USER_MODEL)),
                ('haha', models.ManyToManyField(blank=True, related_name='photo_comment_hahas', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='photo_comment_likes', to=settings.AUTH_USER_MODEL)),
                ('love', models.ManyToManyField(blank=True, related_name='photo_comment_loves', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selfreplies', to='comment.postphotocomment')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_comments', to='social.socialphoto')),
                ('sad', models.ManyToManyField(blank=True, related_name='photo_comment_sads', to=settings.AUTH_USER_MODEL)),
                ('senti', models.ManyToManyField(blank=True, related_name='photo_comment_senties', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_photocomment', to=settings.AUTH_USER_MODEL)),
                ('wow', models.ManyToManyField(blank=True, related_name='photo_comment_wows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
