# Generated by Django 3.2.6 on 2021-08-26 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20210826_1508'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoComment',
        ),
    ]
