# Generated by Django 3.2.6 on 2021-08-28 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0005_delete_photocomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostPhotoCommentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/postphotocommenthistory')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('postphotocomment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='comment.postphotocomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usr_pst_ph_cmnt_hstry', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostCommentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/postcommenthistory')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('postcomment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='comment.postcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_post_comment_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
