# Generated by Django 3.2.6 on 2021-08-12 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('year_of_establishment', models.CharField(blank=True, max_length=100, null=True)),
                ('company_size', models.CharField(blank=True, max_length=100, null=True)),
                ('company_country', models.CharField(blank=True, max_length=100, null=True)),
                ('company_district', models.CharField(blank=True, max_length=100, null=True)),
                ('company_subdistrict', models.CharField(blank=True, max_length=100, null=True)),
                ('industry_category', models.CharField(blank=True, max_length=100, null=True)),
                ('industry_type', models.CharField(blank=True, max_length=100, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('business_description', models.TextField(blank=True, null=True)),
                ('trade_licence_no', models.IntegerField(blank=True, null=True)),
                ('rl_no', models.IntegerField(blank=True, null=True)),
                ('contact_person_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_person_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person_designation', models.CharField(blank=True, max_length=100, null=True)),
                ('facility_for_person_with_disability', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstituionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('vacancies', models.IntegerField(blank=True, null=True)),
                ('functional_job_category', models.CharField(blank=True, max_length=100, null=True)),
                ('special_skills_job_category', models.CharField(blank=True, max_length=100, null=True)),
                ('employment_status', models.CharField(blank=True, max_length=100, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('resume_receiveing_option', models.CharField(blank=True, max_length=100, null=True)),
                ('special_instruction', models.TextField(blank=True, null=True)),
                ('photograph_enclosed', models.BooleanField(blank=True, null=True)),
                ('job_level', models.CharField(blank=True, max_length=100, null=True)),
                ('job_context', models.TextField(blank=True, null=True)),
                ('job_responsibilities', models.TextField(blank=True, null=True)),
                ('workplace', models.CharField(blank=True, max_length=100, null=True)),
                ('job_location', models.CharField(blank=True, max_length=100, null=True)),
                ('min_salary', models.IntegerField(blank=True, null=True)),
                ('max_salary', models.IntegerField(blank=True, null=True)),
                ('per_policy', models.CharField(blank=True, max_length=100, null=True)),
                ('show_salary', models.BooleanField(blank=True, null=True)),
                ('is_compare', models.BooleanField(blank=True, null=True)),
                ('show_alert', models.BooleanField(blank=True, null=True)),
                ('additional_salary_info', models.TextField(blank=True, null=True)),
                ('compensation_and_benefits', models.TextField(blank=True, null=True)),
                ('lunch_facilities', models.CharField(blank=True, max_length=100, null=True)),
                ('salary_review', models.CharField(blank=True, max_length=100, null=True)),
                ('num_of_fastival_bonous', models.IntegerField(blank=True, null=True)),
                ('other', models.TextField(blank=True, null=True)),
                ('degree_level', models.CharField(blank=True, max_length=100, null=True)),
                ('degree_name', models.CharField(blank=True, max_length=100, null=True)),
                ('major_in', models.CharField(blank=True, max_length=100, null=True)),
                ('prefered_educational_institutions', models.TextField(blank=True, null=True)),
                ('other_educational_qualifications', models.TextField(blank=True, null=True)),
                ('training_or_trade_cources', models.TextField(blank=True, null=True)),
                ('professional_certifications', models.TextField(blank=True, null=True)),
                ('experience_required', models.BooleanField(blank=True, null=True)),
                ('min_experience', models.IntegerField(blank=True, null=True)),
                ('max_experience', models.IntegerField(blank=True, null=True)),
                ('fresher_can_apply', models.BooleanField(blank=True, null=True)),
                ('area_of_experience', models.TextField(blank=True, null=True)),
                ('area_of_business', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('additional_requirements', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('min_age', models.IntegerField(blank=True, null=True)),
                ('max_age', models.IntegerField(blank=True, null=True)),
                ('person_with_disability_can_apply', models.BooleanField(blank=True, null=True)),
                ('company_name_show', models.BooleanField(blank=True, null=True)),
                ('company_address_show', models.BooleanField(blank=True, null=True)),
                ('company_business_show', models.BooleanField(blank=True, null=True)),
                ('which_industry_type_to_show', models.CharField(blank=True, max_length=100, null=True)),
                ('is_age', models.BooleanField(blank=True, null=True)),
                ('is_age_mendatory', models.BooleanField(blank=True, null=True)),
                ('is_gender', models.BooleanField(blank=True, null=True)),
                ('is_gender_mendatory', models.BooleanField(blank=True, null=True)),
                ('is_total_year_experience', models.BooleanField(blank=True, null=True)),
                ('is_experience_mendatory', models.BooleanField(blank=True, null=True)),
                ('is_area_of_experience', models.BooleanField(blank=True, null=True)),
                ('is_skills', models.BooleanField(blank=True, null=True)),
                ('is_location', models.BooleanField(blank=True, null=True)),
                ('is_location_mendatory', models.BooleanField(blank=True, null=True)),
                ('is_salary_range', models.BooleanField(blank=True, null=True)),
                ('is_area_of_business', models.BooleanField(blank=True, null=True)),
                ('is_job_level', models.BooleanField(blank=True, null=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobposts', to='employer.employer')),
            ],
        ),
    ]
