# Generated by Django 3.2.6 on 2021-08-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_alter_jobpost_is_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='is_age',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
