# Generated by Django 3.2.6 on 2021-09-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0010_auto_20210906_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='functional_job_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='special_skills_job_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
