# Generated by Django 3.2.6 on 2021-09-06 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0012_auto_20210906_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='functional_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fcat_posts', to='employer.functionaljobcategory'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='special_skills_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spskcat_posts', to='employer.specialskillcategory'),
        ),
    ]
