# Generated by Django 3.2.6 on 2021-09-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0013_auto_20210906_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='NID_no_required',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='cover_letter_required',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='cv_required',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='driving_lisence_no_required',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='passport_required',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='rusume_required',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
