# Generated by Django 3.2.6 on 2021-09-07 20:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20210824_1658'),
        ('employer', '0014_auto_20210908_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('present_salary', models.PositiveBigIntegerField(default=0)),
                ('expected_salary', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(10)])),
                ('working_experience', models.IntegerField(default=0)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='jobspost/cv')),
                ('resume', models.FileField(blank=True, null=True, upload_to='jobspost/resume')),
                ('nid_no', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_no', models.CharField(blank=True, max_length=100, null=True)),
                ('driving_lisence_no', models.CharField(blank=True, max_length=100, null=True)),
                ('shortlisted', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('selected', models.BooleanField(default=False)),
                ('interviewed', models.BooleanField(default=False)),
                ('viewed', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants_list', to='employer.jobpost')),
                ('jobprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobprofile')),
            ],
        ),
    ]
