# Generated by Django 3.2.6 on 2021-09-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0018_jobpost_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='interviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicants',
            name='selected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicants',
            name='shortlisted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
