# Generated by Django 3.2.6 on 2021-09-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0023_auto_20210919_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='industry_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
