# Generated by Django 3.2.6 on 2021-09-19 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0026_employer_i'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='i',
        ),
    ]
