# Generated by Django 3.2.6 on 2021-09-19 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0029_auto_20210919_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='organization_type',
            new_name='industry_type',
        ),
    ]
