# Generated by Django 3.2.6 on 2021-09-20 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0030_rename_organization_type_employer_industry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='industry_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_post', to='employer.industrycategory'),
        ),
    ]
