# Generated by Django 3.2.6 on 2021-09-22 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_benefitlist_businesslist_experiencelist_functionaljobcategory_industrycategory_instituionlist_locati'),
        ('employer', '0033_jobpost_is_featured'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BenefitList',
        ),
        migrations.DeleteModel(
            name='BusinessList',
        ),
        migrations.DeleteModel(
            name='ExperienceList',
        ),
        migrations.DeleteModel(
            name='InstituionList',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='SkillsList',
        ),
        migrations.AlterField(
            model_name='employer',
            name='functional_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fun_orgs', to='jobs.functionaljobcategory'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='industry_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orgs', to='jobs.industrycategory'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='industry_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orgs_ty', to='jobs.organizationtype'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='functional_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fcat_posts', to='jobs.functionaljobcategory'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='industry_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_post', to='jobs.industrycategory'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='special_skills_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spskcat_posts', to='jobs.specialskillcategory'),
        ),
        migrations.DeleteModel(
            name='FunctionalJobCategory',
        ),
        migrations.DeleteModel(
            name='IndustryCategory',
        ),
        migrations.DeleteModel(
            name='OrganizationType',
        ),
        migrations.DeleteModel(
            name='SpecialSkillCategory',
        ),
    ]
