# Generated by Django 3.2.6 on 2021-10-03 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_rename_country_city_state'),
        ('employer', '0034_auto_20210922_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations_posts', to='jobs.city'),
        ),
    ]
