# Generated by Django 3.2.6 on 2021-10-06 09:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employer', '0036_jobpost_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderating_org', to=settings.AUTH_USER_MODEL),
        ),
    ]
