# Generated by Django 3.2.6 on 2021-10-07 08:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employer', '0037_employer_moderators'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='pending_moderators',
            field=models.ManyToManyField(blank=True, related_name='pending_moderating_org', to=settings.AUTH_USER_MODEL),
        ),
    ]
