# Generated by Django 3.2.6 on 2021-10-23 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_license', models.FileField(blank=True, null=True, upload_to='sellbuy/tradelicense')),
                ('electric_bill1', models.FileField(blank=True, null=True, upload_to='sellbuy/electric_bill')),
                ('electric_bill2', models.FileField(blank=True, null=True, upload_to='sellbuy/electric_bill')),
                ('owner_proof', models.FileField(blank=True, null=True, upload_to='sellbuy/owner_proof')),
                ('contract_copy', models.FileField(blank=True, null=True, upload_to='sellbuy/owner_proof')),
                ('shop_address', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_photo', models.ImageField(blank=True, null=True, upload_to='sellbuy/photo')),
                ('owner_nid_no', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_nid_photo', models.FileField(blank=True, null=True, upload_to='sellbuy/nid')),
                ('nominee_photo', models.ImageField(blank=True, null=True, upload_to='sellbuy/photo')),
                ('nominee_nid_no', models.CharField(blank=True, max_length=100, null=True)),
                ('nominee_nid_photo', models.FileField(blank=True, null=True, upload_to='sellbuy/nid')),
                ('nominee_present_address', models.CharField(blank=True, max_length=100, null=True)),
                ('nominee_permanent_address', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
