# Generated by Django 3.2.6 on 2021-10-23 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellbuy', '0002_auto_20211023_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='owner_nid_no',
        ),
    ]
