# Generated by Django 3.2.6 on 2021-10-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellbuy', '0003_remove_sellerprofile_owner_nid_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='is_varified',
            field=models.BooleanField(default=False),
        ),
    ]
