# Generated by Django 3.2.6 on 2021-11-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellbuy', '0006_auto_20211101_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='buy_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
