# Generated by Django 3.2.6 on 2021-11-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellbuy', '0007_alter_product_buy_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='selled_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
