# Generated by Django 3.2.6 on 2021-11-07 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellbuy', '0010_auto_20211104_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewreplies', to='sellbuy.review'),
        ),
    ]
