# Generated by Django 3.2.6 on 2021-10-30 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_management', '0005_auto_20211006_1454'),
        ('metrimony', '0022_auto_20211028_1555'),
        ('employer', '0040_employer_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.TextField()),
                ('report_image', models.ImageField(blank=True, null=True, upload_to='reports/images')),
                ('type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumer_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumer_reports', to='user_management.consumer')),
                ('employer_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_reports', to='employer.employer')),
                ('jobpost_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobpost_reports', to='employer.jobpost')),
                ('matri_pro_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matri_reports', to='metrimony.personal_info')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
