# Generated by Django 3.2.6 on 2021-08-12 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_no', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_issue_date', models.DateField(blank=True, null=True)),
                ('emergency_contact_no', models.CharField(blank=True, max_length=100, null=True)),
                ('alternative_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('portfolio_link', models.URLField(blank=True, null=True)),
                ('career_objective', models.TextField(blank=True, null=True)),
                ('present_salary', models.IntegerField(blank=True, null=True)),
                ('expected_salary', models.IntegerField(blank=True, null=True)),
                ('looking_job_level', models.CharField(blank=True, max_length=100, null=True)),
                ('available_for_job_type', models.CharField(blank=True, max_length=100, null=True)),
                ('job_location', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('organizations', models.CharField(blank=True, max_length=100, null=True)),
                ('career_summary', models.TextField(blank=True, null=True)),
                ('special_qualifications', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('cv_photo', models.ImageField(blank=True, null=True, upload_to='jobs/images')),
                ('cv_upload', models.FileField(blank=True, null=True, upload_to='jobs/cv')),
                ('job_categories', models.ManyToManyField(related_name='categoris', to='jobs.JobCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Special_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('topic_covered', models.CharField(blank=True, max_length=100, null=True)),
                ('training_year', models.IntegerField(blank=True, null=True)),
                ('institute', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('jobprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training', to='jobs.jobprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(blank=True, max_length=100, null=True)),
                ('learned_by', models.CharField(blank=True, max_length=100, null=True)),
                ('jobprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='jobs.jobprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('relation', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_off', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_res', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('jobprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference', to='jobs.jobprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('tools', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('contribution', models.CharField(blank=True, max_length=100, null=True)),
                ('is_live', models.CharField(blank=True, max_length=100, null=True)),
                ('learings', models.TextField(blank=True, null=True)),
                ('jobprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='jobs.jobprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Professional_certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.CharField(blank=True, max_length=100, null=True)),
                ('institute', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('jobprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_certificate', to='jobs.jobprofile')),
            ],
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='special_skills',
            field=models.ManyToManyField(related_name='skills', to='jobs.Special_skills'),
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jobprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_business', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('Area_of_experience', models.TextField(blank=True, null=True)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('company_location', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('jobprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='jobs.jobprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EducationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_of_edu', models.CharField(blank=True, max_length=100, null=True)),
                ('degree_or_exam', models.CharField(blank=True, max_length=100, null=True)),
                ('major_in', models.CharField(blank=True, max_length=100, null=True)),
                ('institude_name', models.CharField(blank=True, max_length=100, null=True)),
                ('result', models.CharField(blank=True, max_length=100, null=True)),
                ('cgpa', models.FloatField(blank=True, null=True)),
                ('scale', models.IntegerField(blank=True, null=True)),
                ('year_of_passing', models.IntegerField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('achievement', models.CharField(blank=True, max_length=100, null=True)),
                ('jobprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='jobs.jobprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Disability_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_disability_id', models.CharField(blank=True, max_length=100, null=True)),
                ('show_on_resume', models.BooleanField(default=False)),
                ('disability_to_see', models.CharField(blank=True, max_length=100, null=True)),
                ('disability_to_hear', models.CharField(blank=True, max_length=100, null=True)),
                ('disability_to_communicate', models.CharField(blank=True, max_length=100, null=True)),
                ('disability_to_concentrade', models.CharField(blank=True, max_length=100, null=True)),
                ('disability_to_remember', models.CharField(blank=True, max_length=100, null=True)),
                ('disability_to_sit_stand_walk_climbStairs', models.CharField(blank=True, max_length=100, null=True)),
                ('disability_to_taking_care', models.CharField(blank=True, max_length=100, null=True)),
                ('jobprofile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disability', to='jobs.jobprofile')),
            ],
        ),
    ]
