# Generated by Django 3.2.6 on 2021-08-16 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmryExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ba_no', models.CharField(blank=True, max_length=100, null=True)),
                ('ranks', models.CharField(blank=True, max_length=100, null=True)),
                ('types', models.CharField(blank=True, max_length=100, null=True)),
                ('arms', models.CharField(blank=True, max_length=100, null=True)),
                ('trade', models.CharField(blank=True, max_length=100, null=True)),
                ('cource', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_commission', models.DateField(blank=True, null=True)),
                ('date_of_retirement', models.DateField(blank=True, null=True)),
                ('jobprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='army', to='jobs.jobprofile')),
            ],
        ),
    ]
