# Generated by Django 3.2.6 on 2021-08-16 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_amryexperience'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AmryExperience',
            new_name='ArmyExperience',
        ),
    ]
