# Generated by Django 3.2.6 on 2021-08-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_amryexperience_armyexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='armyexperience',
            name='ba_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
