# Generated by Django 3.2.6 on 2021-08-16 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_armyexperience_ba_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='armyexperience',
            old_name='cource',
            new_name='course',
        ),
    ]
