# Generated by Django 3.2.6 on 2021-09-22 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20210824_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobprofile',
            name='job_categories',
        ),
        migrations.RemoveField(
            model_name='jobprofile',
            name='special_skills',
        ),
    ]
