# Generated by Django 3.2.6 on 2021-09-22 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20210922_1240'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobCategory',
        ),
        migrations.DeleteModel(
            name='Special_skills',
        ),
    ]
