# Generated by Django 3.2.6 on 2021-09-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_benefitlist_businesslist_experiencelist_functionaljobcategory_industrycategory_instituionlist_locati'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='job_categories',
            field=models.ManyToManyField(blank=True, related_name='categoris', to='jobs.FunctionalJobCategory'),
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='special_skills',
            field=models.ManyToManyField(blank=True, related_name='skills', to='jobs.SpecialSkillCategory'),
        ),
    ]
