# Generated by Django 3.2.6 on 2021-09-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20210922_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
