# Generated by Django 3.2.6 on 2021-10-03 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_alter_city_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='country',
            new_name='state',
        ),
    ]
