# Generated by Django 3.2.6 on 2021-10-04 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_rename_country_city_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobprofile',
            name='job_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations_profiles', to='jobs.city'),
        ),
    ]
