# Generated by Django 3.2.6 on 2021-10-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_alter_jobprofile_job_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobprofile',
            name='job_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
