# Generated by Django 3.2.6 on 2021-10-04 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_alter_jobprofile_job_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
